FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# PATH isn't actually set in the Docker image, so we have to set it from within the container
RUN $newPath = ('C:\nodejs;{0}\Yarn\bin;{1}' -f $env:LOCALAPPDATA, $env:PATH); \
	Write-Host ('Updating PATH: {0}' -f $newPath); \
	[Environment]::SetEnvironmentVariable('PATH', $newPath, [EnvironmentVariableTarget]::Machine)
# doing this first to share cache across versions more aggressively


RUN $url = 'https://aka.ms/vs/17/release/vc_redist.x64.exe'; \
	Write-Host ('Downloading {0} ...' -f $url); \
	Invoke-WebRequest -Uri $url -OutFile vcredist_x64.exe; \
	\
	Write-Host ('Installing vcredist_x64.exe ...'); \
	Start-Process -filepath "vcredist_x64.exe" -ArgumentList "/install", "/passive", \
	"/norestart", "'/log c:/temp/a.txt'" -PassThru | wait-process; \
	\
	Write-Host 'Removing vcredist_x64.exe ...'; \
	Remove-Item vcredist_x64.exe -Force; \
	\
	Write-Host 'Complete.'


ENV NODE_VERSION 16.9.1
ENV NODE_SHA256 44b36846f45c3599d4230008cc5064d3e72405eea26268731b2374fe4ab998ed

RUN $url = ('https://nodejs.org/dist/v{0}/node-v{0}-win-x64.zip' -f $env:NODE_VERSION); \
	Write-Host ('Downloading {0} ...' -f $url); \
	Invoke-WebRequest -Uri $url -OutFile 'node.zip'; \
	\
	Write-Host ('Verifying sha256 ({0}) ...' -f $env:NODE_SHA256); \
	if ((Get-FileHash node.zip -Algorithm sha256).Hash -ne $env:NODE_SHA256) { throw 'SHA256 mismatch' }; \
	\
	Write-Host 'Expanding ...'; \
	Expand-Archive node.zip -DestinationPath C:\; \
	\
	Write-Host 'Renaming ...'; \
	Rename-Item -Path ('C:\node-v{0}-win-x64' -f $env:NODE_VERSION) -NewName 'C:\nodejs'; \
	\
	Write-Host 'Removing ...'; \
	Remove-Item node.zip -Force; \
	\
	Write-Host 'Updating npm ("npm install -g npm@8.12.2") ...'; \
	npm install -g npm@8.12.2; \
	\
	Write-Host 'Verifying ("node --version") ...'; \
	node --version; \
	Write-Host 'Verifying ("npm --version") ...'; \
	npm --version; \
	\
	Write-Host 'Complete.'

ENV YARN_VERSION 1.22.19

# "It is recommended to install Yarn through the npm package manager" (https://classic.yarnpkg.com/en/docs/install)
RUN Write-Host 'Installing "yarn" ...'; \
	npm install --global ('yarn@{0}' -f $env:YARN_VERSION); \
	\
	Write-Host 'Verifying ("yarn --version") ...'; \
	yarn --version; \
	\
	Write-Host 'Complete.'

CMD [ "node" ]
