# escape=`


FROM mcr.microsoft.com/windows/nanoserver:ltsc2022

USER ContainerAdministrator

ENTRYPOINT ["/bin/drone-cache"]

ARG CACHE_VERSION=1.2.2

RUN `
    mkdir tmp && mkdir bin`
    && curl -sSfLo tmp/file.zip https://github.com/meltwater/drone-cache/releases/download/v%CACHE_VERSION%/drone-cache_%CACHE_VERSION%_Windows_x86_64.zip `
    && tar -C bin -oxzf tmp/file.zip --strip 1 drone-cache_%CACHE_VERSION%_Windows_x86_64/drone-cache.exe`
    && rmdir /Q /S tmp `
    && /bin/drone-cache --version
