# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2022

RUN `
  mkdir tmp && mkdir git`
	&& curl -sSfLo tmp/file.zip https://github.com/git-for-windows/git/releases/download/v2.34.1.windows.1/MinGit-2.34.1-64-bit.zip `
  && tar -C c:\git -oxzf tmp/file.zip`
  && rmdir /Q /S tmp

# Add git to PATH
RUN setx /M PATH "%PATH%;C:/git/cmd;C:/git/mingw64/bin;C:/git/usr/bin"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
