# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2022

RUN `
  mkdir tmp && mkdir git`
  && curl -sSfLo tmp/file.zip https://github.com/git-for-windows/git/releases/download/v2.39.1.windows.1/MinGit-2.39.1-64-bit.zip `
  && tar -C c:\git -oxzf tmp/file.zip`
  && rmdir /Q /S tmp

RUN `
  mkdir tmp`
  && curl -sSfLo tmp/file.zip https://github.com/git-lfs/git-lfs/releases/download/v3.3.0/git-lfs-windows-amd64-v3.3.0.zip `
  && tar -C tmp -oxzf tmp/file.zip`
  && robocopy tmp/git-lfs-3.3.0 c:\git\usr\bin /s /e || exit 0`
  && rmdir /Q /S tmp

# Add git to PATH
RUN setx /M PATH "%PATH%;C:/git/cmd;C:/git/mingw64/bin;C:/git/usr/bin"

# Add Drone-CI workbench folder to safe directories to prevent error du to different user cloning
# E.g. the drone-git plugin uses the ContainerAdministrator user
RUN git config --global --add safe.directory C:/drone/src/

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
