name: Publish container

on:
  workflow_dispatch:
    inputs:
      submodule:
        required: true
        type: choice
        description: Submodule to build and push
        options:
          - drone-gitea-release
          - drone-git
          - drone-runner-docker
          - drone-cache
          - drone-s3
          - drone-s3-cache
          - mingit
          - nodejs

jobs:
  build:
    name: Publish ${{ github.event.inputs.submodule }}
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Determine Project Build Variables
        id: build_vars
        shell: python
        run: |
          project = "${{ github.event.inputs.submodule }}"
          main_go_path = "."

          if project == "drone-gitea-release":
              go_build_object = "release/windows/amd64/drone-gitea-release.exe"
              docker_file = f"{project}/docker/Dockerfile.windows.2022"
          elif project == "drone-git":
              go_build_object = "None"
              docker_file = f"{project}/docker/Dockerfile.windows.2022"
          elif project == "drone-runner-docker":
              go_build_object = "release/windows/amd64/drone-runner-docker.exe"
              docker_file = f"{project}/docker/Dockerfile.windows.amd64.2022"
          elif project == "drone-cache":
              go_build_object = "None"
              docker_file = f"{project}/docker/Dockerfile.windows.2022"
          elif project == "drone-s3":
              go_build_object = "release/windows/amd64/drone-s3.exe"
              docker_file = f"{project}/docker/Dockerfile.windows.2022"
          elif project == "drone-s3-cache":
              go_build_object = "release/windows/amd64/drone-s3-cache.exe"
              docker_file = f"{project}/docker/Dockerfile.windows.2022"
              main_go_path = "./cmd/drone-s3-cache"
          elif project == "mingit":
              go_build_object = "None"
              docker_file = f"{project}/docker/Dockerfile.windows.2022"
          elif project == "nodejs":
              go_build_object = "None"
              docker_file = f"{project}/docker/Dockerfile.windows.2022"
          else:
              raise SystemExit(1)

          print(f"::set-output name=go_build_object::{go_build_object}")
          print(f"::set-output name=docker_file::{docker_file}")
          print(f"::set-output name=main_go_path::{main_go_path}")

      - name: Setup Go
        if: ${{ steps.build_vars.outputs.go_build_object != 'None' }}
        uses: actions/setup-go@v4

      - name: Build go code
        if: ${{ steps.build_vars.outputs.go_build_object != 'None' }}
        run: |
          cd ${{ github.event.inputs.submodule }}
          go vet ./...
          go build -v -o ${{ steps.build_vars.outputs.go_build_object }} ${{ steps.build_vars.outputs.main_go_path }}

      - name: Build and push image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.inputs.submodule }}
          tags: ltsc2022
          registry: ghcr.io
          dockerfile: ${{ steps.build_vars.outputs.docker_file }}
          directory: ${{ github.event.inputs.submodule }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
