name: Publish container

on:
  workflow_dispatch:
    inputs:
      submodule:
        required: true
        type: choice
        description: Submodule to build and push
        options:
          - drone-gitea-release

jobs:
  build:
    name: Publish ${{ github.event.inputs.submodule }}
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Build go code
        run: |
          cd ${{ github.event.inputs.submodule }}
          go vet ./...
          go build -v -o release/windows/amd64/drone-gitea-release.exe

      - name: Build and push image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ github.event.inputs.submodule }}
          tags: ltsc2022
          registry: ghcr.io
          dockerfile: ${{ github.event.inputs.submodule }}/docker/Dockerfile.windows.2022
          directory: ${{ github.event.inputs.submodule }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
